### ISSUE TITLE
Client: Inhalte werden nicht gespeichert, wenn Lektion nicht abgeschlossen wird

### ISSUE THREAD

**Issue by louisabauer** [peterfromberger/mt-frontend#16]
Wenn man sich durch eine Lektion durchgeklickt hat und die Weiterleitung auf die nächste Seite nicht funktioniert, muss man dieselbe Seite nochmal von vorne ausfüllen. Das ist etwas frustrierend.

**Comment by peterfromberger** [comment]
Jede Aufgabe wird nun einzeln gespeichert, nicht erst nach Beedigung der Lektion.
