### ISSUE TITLE
Client: gleiche Farbe für "Fehlermeldungen" und "Nachteile" irritierend

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend#28]
Bspw. Bei Modul 1 Sitzung 2 Lektion 3
![design2](https://user-images.githubusercontent.com/50660709/57856230-da4d5880-77ec-11e9-95ce-7637bdec664b.PNG)

**Comment by peterfromberger** [comment]
jetzt sind alle Chips in der accent-Farbe
