### ISSUE TITLE
Client: In Wagtail veränderte Sitzungsreihenfolge wird nicht übernommen

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend#39]

**Comment by SonjaSchroeder** [comment]
Tamara hat mir eben gezeigt, dass es geht, wenn man auf "Sort" klickt

![grafik](https://user-images.githubusercontent.com/50660709/66471002-eb904d80-ea8a-11e9-8801-8a4589682628.png)

**Comment by peterfromberger** [comment]
Nun geht das so nicht mehr; die Reihenfolge wird ausschließlich über die Angabe in Wagtail bestimmt (Nr der Lektion)
