### ISSUE TITLE
Client: Fill in the Gaps Task wird nicht richtig umgesetzt in Frontend

### ISSUE THREAD

**Issue by SafiyeTozdan** [peterfromberger/mt-frontend#59]

**Comment by peterfromberger** [comment]
Hey Safi,
hast du denn die Gaps und die dazugehörigen Wörter im richtigen format eingegeben? Im wagtail steht unterhlab der Aufgabe ein Hinweis dazu...

**Comment by SafiyeTozdan** [comment]
![fill in the gaps](https://user-images.githubusercontent.com/53052450/62463399-34c1d980-b78a-11e9-8615-35557792c1b6.jpg)

**Comment by SafiyeTozdan** [comment]
Ist das so falsch?

**Comment by SafiyeTozdan** [comment]
hat sich erledigt!
