### ISSUE TITLE
Client: Keine gute Hilfe, wenn Aufgabe falsch ist bei Fill in The Gap Assignment Task

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend#79]
![grafik](https://user-images.githubusercontent.com/50660709/65669440-d7d4f800-e043-11e9-81a0-8296b6adbb76.png)

Kannst du bei der Antwortüberprüfung genau angeben, welche Items falsch sind? Sonst könnten manche Teilnehmer bei solchen Aufgaben hängen bleiben.

**Comment by peterfromberger** [comment]
Wird nun farblich für jedes Wort gekennzeichnet, ob es richtig oder falsch zugeordnet wurde...
